# Generated by Django 4.0 on 2022-01-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0011_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(max_length=30, verbose_name='Google Customer ID'),
        ),
    ]
