# Generated by Django 3.2.8 on 2021-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Middle Name'),
        ),
    ]
