# Generated by Django 3.2.8 on 2021-10-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='inventory',
        ),
    ]
