# Generated by Django 3.2.8 on 2021-10-25 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_transaction_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 25), verbose_name='Appointment Date'),
            preserve_default=False,
        ),
    ]
