# Generated by Django 3.2.8 on 2021-10-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_transaction_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default=0, max_length=30, verbose_name='Google Customer ID'),
            preserve_default=False,
        ),
    ]
