# Generated by Django 3.2.8 on 2021-10-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_date'),
        ('api', '0007_user_customer_id'),
    ]

    operations = [
    ]
