# Generated by Django 3.2.8 on 2021-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0007_appointment_date_0007_user_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://www.gravatar.com/avatar/?d=mp', verbose_name='Profile Image URL'),
        ),
    ]
