# Generated by Django 3.2.8 on 2021-10-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(default='https://www.gravatar.com/avatar/?d=mp', max_length=256, verbose_name='Profile Image URL'),
        ),
    ]
