name: code_quality

on: [push]

jobs:
  code_quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
        pylint `find . -type d -name migrations -prune -o -name '*.py'| grep -v __ |xargs`
    - name: Python Blacken
      uses: piotrpawlaczek/python-blacken@release/stable
      with:
        only-check: 'no'
        
